name: Build All
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Add execution right to gradlew
        run: chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1

      - name: Install Android SDK
        run: sdkmanager "platform-tools" "platforms;android-35"

      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '16.1'

      - name: Build the library
        run: ./gradlew build --no-daemon --stacktrace --info --scan

      - name: Check bump
        id: vbump
        uses: rgryta/Check-Bump@main
        with:
          method: 'regex'
          path: 'library/version.properties'
          prefix: 'v'

      - name: Publish the library
        if: steps.vbump.outputs.bump == 'true'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        run: ./gradlew publish --no-daemon --stacktrace --info --scan